### ISSUE TITLE
[@angular-eslint/schematics] Added to angular.json as "schematicCollections" breaks "ng generate" command

### ISSUE THREAD

**Issue by MIKOLAJW197** [angular-eslint/angular-eslint#1289]
Hi,
While configuring new project (newest Angular etc.) found some strange behaviour.

While trying to run for example:
`ng g module some-name`

I get this error:
```
An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
See "/private/var/folders/x3/83gbflv10xjcccl2b5_3w8th0000gp/T/ng-pFSr6U/angular-errors.log" for further details.
```

Looking at the log file:
```
[error] TypeError: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
    at GenerateCommandModule.getSchematics (/Users/mikolajwolicki/Desktop/githome/phoenix-2/node_modules/@angular/cli/src/commands/generate/cli.js:141:29)
    at getSchematics.next (<anonymous>)
    at GenerateCommandModule.getSchematicsToRegister (/Users/mikolajwolicki/Desktop/githome/phoenix-2/node_modules/@angular/cli/src/commands/generate/cli.js:158:76)
    at async GenerateCommandModule.builder (/Users/mikolajwolicki/Desktop/githome/phoenix-2/node_modules/@angular/cli/src/commands/generate/cli.js:35:55)
    at async runCommand (/Users/mikolajwolicki/Desktop/githome/phoenix-2/node_modules/@angular/cli/src/command-builder/command-runner.js:113:5)
    at async default_1 (/Users/mikolajwolicki/Desktop/githome/phoenix-2/node_modules/@angular/cli/lib/cli/index.js:70:16)
```

**After removing cli property from Angular.json file - everything works correctly**

ENV info to reproduce:
Package.JSON:
```
"dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.2",
    "@angular-eslint/builder": "15.2.0",
    "@angular-eslint/eslint-plugin": "15.2.0",
    "@angular-eslint/eslint-plugin-template": "15.2.0",
    "@angular-eslint/schematics": "15.2.0",
    "@angular-eslint/template-parser": "15.2.0",
    "@angular/cli": "~15.1.2",
    "@angular/compiler-cli": "^15.1.0",
    "@types/jasmine": "~4.3.0",
    "@typescript-eslint/eslint-plugin": "5.48.1",
    "@typescript-eslint/parser": "5.48.1",
    "eslint": "^8.31.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "husky": "^8.0.3",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "lint-staged": "^13.1.0",
    "prettier": "^2.8.3",
    "prettier-eslint": "^15.0.1",
    "typescript": "~4.9.4"
  },
  ```

Angular.json with added:
```
...
  "cli": {
    "schematicCollections": ["@angular-eslint/schematics"]
  }
....
```

**Comment by JamesHenry** [comment]
This was an Angular CLI bug which has already been fixed https://github.com/angular/angular-cli/issues/24586

**Comment by MIKOLAJW197** [comment]
Thx!
