### ISSUE TITLE
Error while loading rule '@angular-eslint/template/banana-in-box': You have used a rule which requires '@angular-eslint/template-parser' to be used as the 'parser' in your ESLint config.

### ISSUE THREAD

**Issue by SDAdham** [angular-eslint/angular-eslint#1325]
**Description and reproduction of the issue**

I have the following HTML eslint config as here:
```
{
      "files": [
        "*.html"
      ],
  "parser": "@angular-eslint/template-parser", //tried without this
  "extends": [
    "plugin:@angular-eslint/template/recommended", // tried without this
    "plugin:prettier/recommended" // tried without this
  ],
  "plugins": [
    "html",
    "@angular-eslint/template" // tried without this
  ],
  "rules": {
    "@angular-eslint/template/eqeqeq": "off",
    "prettier/prettier": [
      "error",
      {
        "parser": "angular"
      }
    ]
  }
}
```

I get the following error:

```
Error while loading rule '@angular-eslint/template/banana-in-box': You have used a rule which requires '@angular-eslint/template-parser' to be used as the 'parser' in your ESLint config.
Occurred while linting <proj-dir>\src\index.html
    at ensureTemplateParser (<proj-dir>\node_modules\@angular-eslint\utils\dist\eslint-plugin-template\parser-services.js:21:15)
    at Object.getTemplateParserServices (<proj-dir>\node_modules\@angular-eslint\utils\dist\eslint-plugin-template\parser-services.js:5:5)
    at create (<proj-dir>\@angular-eslint\eslint-plugin-template\dist\index.js:1:29313)
    at Object.create (<proj-dir>\node_modules\@angular-eslint\eslint-plugin-template\dist\index.js:1:2746)
    at createRuleListeners (<proj-dir>\node_modules\eslint\lib\linter\linter.js:926:21)
    at <proj-dir>\node_modules\eslint\lib\linter\linter.js:1108:110
    at Array.forEach (<anonymous>)
    at runRules (<proj-dir>\node_modules\eslint\lib\linter\linter.js:1045:34)
    at Linter._verifyWithoutProcessors (<proj-dir>\node_modules\eslint\lib\linter\linter.js:1397:31)
    at verifyCodePart (<proj-dir>\node_modules\eslint-plugin-html\src\index.js:194:36)
```

all of the above being said, all of them has been tried in combination of each other and without each other trying to figure out a workaround.

Which is used by an override to 
**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/template-parser`  | `15.2.1` |
| `ESLint`                           | `8.36.0` |
| `node`                             | `18.15.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 15.2.4
Node: 18.15.0
Package Manager: yarn 3.4.1
OS: win32 x64

Angular: 15.2.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.2
@angular-devkit/build-angular   15.2.4
@angular-devkit/core            15.2.4
@angular-devkit/schematics      15.2.4
@nguniversal/builders           15.2.0
@nguniversal/express-engine     15.2.0
@schematics/angular             15.2.4
rxjs                            7.8.0
typescript                      4.9.5
webpack                         5.76.2
```

- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
@SDAdham I would strongly encourage you to provide a minimal reproduction of the issue on a fresh angular workspace.

A) we would need one to help troubleshoot
B) the act of doing so would likely help uncover the configuration issue

This rule and its usage has not changed for years, and is integration tests on every commit, so it is very likely a configuration issue on your side.

Please feel free to reopen this if you have some steps to reproduce on a fresh Angular CLI workspace
