### ISSUE TITLE
Inline template throws TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by manju-reddys** [angular-eslint/angular-eslint#137]
My component

```
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
   selector: 'ard-root',
   template: `<router-outlet></router-outlet>`,
})
export class AppComponent {
   constructor(private http: HttpClient) {}
}
```

ERROR:

`<<project>>` is redacted.

```
TypeError: Cannot read property 'forEach' of undefined
Occurred while linting <<project>>/src/app/app.component.ts/1_inline-template.component.html:1
    at Program (<<project>>/node_modules/eslint-plugin-import/lib/rules/no-deprecated.js:91:62)
    at <<project>>/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (<<project>>/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (<<project>>/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (<<project>>/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (<<project>>/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (<<project>>/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at <<project>>/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)

```
.eslintrc.js:

```
module.exports = {
   env: {
      browser: true,
      es6: true,
      node: true,
   },
   extends: [
      'prettier',
      'eslint:recommended',
      'plugin:@typescript-eslint/recommended',
      'plugin:prettier/recommended',
      'plugin:@angular-eslint/recommended',
      'plugin:import/typescript',
      'plugin:import/warnings',
      'plugin:import/errors',
   ],
   parser: '@typescript-eslint/parser',
   parserOptions: {
      project: './tsconfig.json',
      sourceType: 'module',
      ecmaVersion: 2020,
   },
   settings: {
      'import/resolver': {
         typescript: { alwaysTryTypes: true },
      },
   },
   plugins: [
      '@typescript-eslint',
      '@nrwl/eslint-plugin-nx',
      '@angular-eslint',
      'jest',
      'import',
   ],
   rules: {
      '@nrwl/nx/enforce-module-boundaries': [
         'error',
         {
            allow: [],
            depConstraints: [],
         },
      ],
      '@angular-eslint/no-conflicting-lifecycle': 'error',
      '@angular-eslint/no-host-metadata-property': 'error',
      '@angular-eslint/no-input-rename': 'error',
      '@angular-eslint/no-inputs-metadata-property': 'error',
      '@angular-eslint/no-output-native': 'error',
      '@angular-eslint/no-output-on-prefix': 'error',
      '@angular-eslint/no-output-rename': 'error',
      '@angular-eslint/no-outputs-metadata-property': 'error',
      '@angular-eslint/use-lifecycle-interface': 'error',
      '@angular-eslint/use-pipe-transform-interface': 'error',
      '@typescript-eslint/consistent-type-definitions': 'error',
      '@typescript-eslint/dot-notation': 'off',
      '@typescript-eslint/explicit-member-accessibility': [
         'off',
         {
            accessibility: 'explicit',
         },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/member-ordering': 'error',
      '@typescript-eslint/naming-convention': 'error',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-empty-interface': 'error',
      '@typescript-eslint/no-inferrable-types': [
         'error',
         {
            ignoreParameters: true,
         },
      ],
      '@typescript-eslint/no-misused-new': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unused-expressions': 'error',
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/unified-signatures': 'error',
      'arrow-body-style': 'error',
      'constructor-super': 'error',
      eqeqeq: ['error', 'smart'],
      'guard-for-in': 'error',
      'id-blacklist': 'off',
      'id-match': 'off',
      'import/no-deprecated': 'warn',
      'no-bitwise': 'off',
      'no-caller': 'error',
      'no-console': [
         'error',
         {
            allow: [
               'log',
               'warn',
               'dir',
               'timeLog',
               'assert',
               'clear',
               'count',
               'countReset',
               'group',
               'groupEnd',
               'table',
               'dirxml',
               'error',
               'groupCollapsed',
               'Console',
               'profile',
               'profileEnd',
               'timeStamp',
               'context',
            ],
         },
      ],
      'no-debugger': 'error',
      'no-empty': 'off',
      'no-eval': 'error',
      'no-fallthrough': 'error',
      'no-new-wrappers': 'error',
      'no-restricted-imports': ['error', 'rxjs/Rx'],
      'no-shadow': [
         'error',
         {
            hoist: 'all',
         },
      ],
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'off',
      'no-var': 'error',
      'prefer-const': 'error',
      radix: 'error',
   },
   /**
    * -----------------------------------------------------
    * NOTES ON CONFIGURATION STRUCTURE ANGULAR SPECIFIC
    * -----------------------------------------------------
    *
    * Out of the box, ESLint does not support TypeScript or HTML. Naturally those are the two
    * main file types we care about in Angular projects, so we have to do a little extra work
    * to configure ESLint exactly how we need to.
    *
    * Fortunately, ESLint gives us an 'overrides' configuration option which allows us to set
    * different lint tooling (parser, plugins, rules etc) for different file types, which is
    * critical because our .ts files require a different parser and different rules to our
    * .html (and our inline Component) templates.
    */
   overrides: [
      /**
       * -----------------------------------------------------
       * TYPESCRIPT FILES (COMPONENTS, SERVICES ETC) (.ts)
       * -----------------------------------------------------
       */
      {
         files: ['*.ts'],
         /**
          * We use a dedicated tsconfig file for the compilation related to linting so that we
          * have complete control over what gets included and we can maximize performance
          */
         parserOptions: {
            project: './tsconfig.eslint.json',
            sourceType: 'module',
            ecmaVersion: 2020,
         },
         /**
          * See packages/eslint-plugin/src/configs/README.md
          * for what this recommended config contains.
          */
         extends: ['plugin:@angular-eslint/recommended'],
         rules: {
            /**
             * Any TypeScript related rules you wish to use/reconfigure over and above the
             * recommended set provided by the @angular-eslint project would go here.
             *
             * There are some examples below from the multiple plugins and ESLint core:
             */

            // ORIGINAL tslint.json -> 'directive-selector': [true, 'attribute', 'app', 'camelCase'],
            '@angular-eslint/directive-selector': [
               'error',
               { type: 'attribute', prefix: 'portals', style: 'camelCase' },
            ],

            // ORIGINAL tslint.json -> 'component-selector': [true, 'element', 'app', 'kebab-case'],
            '@angular-eslint/component-selector': [
               'error',
               { type: 'element', prefix: 'portals', style: 'kebab-case' },
            ],

            quotes: ['error', 'single', { allowTemplateLiterals: true }],

            '@typescript-eslint/no-misused-promises': ['error'],
         },
      },

      /**
       * -----------------------------------------------------
       * COMPONENT TEMPLATES
       * -----------------------------------------------------
       *
       * If you use inline templates, make sure you read the notes on the configuration
       * object after this one to understand how they relate to this configuration directly
       * below.
       */
      {
         files: ['*.component.html'],
         /**
          * See packages/eslint-plugin-template/src/configs/README.md
          * for what this recommended config contains.
          */
         extends: ['plugin:@angular-eslint/template/recommended'],
         rules: {
            /**
             * Any template/HTML related rules you wish to use/reconfigure over and above the
             * recommended set provided by the @angular-eslint project would go here.
             *
             * There is an example below from ESLint core (note, this specific example is not
             * necessarily recommended for all projects):
             */
            'max-len': ['error', { code: 140 }],
         },
      },

      /**
       * -----------------------------------------------------
       * EXTRACT INLINE TEMPLATES (from within .component.ts)
       * -----------------------------------------------------
       *
       * This extra piece of configuration is necessary to extract inline
       * templates from within Component metadata, e.g.:
       *
       * @Component({
       *  template: `<h1>Hello, World!</h1>`
       * })
       * ...
       *
       * It works by extracting the template part of the file and treating it as
       * if it were a full .html file, and it will therefore match the configuration
       * specific for *.component.html above when it comes to actual rules etc.
       *
       * NOTE: This processor will skip a lot of work when it runs if you don't use
       * inline templates in your projects currently, so there is no great benefit
       * in removing it, but you can if you want to.
       *
       * You won't specify any rules here. As noted above, the rules that are relevant
       * to inline templates are the same as the ones defined for *.component.html.
       */
      {
         files: ['*.component.ts'],
         extends: ['plugin:@angular-eslint/template/process-inline-templates'],
      },
   ],
};

```

**Comment by JamesHenry** [comment]
Hi @manju-reddys - as you can see in the documentation comments you have included above, and in the integration-tests, the key enabler of Angular + ESLint is that we need different file types to have fundamentally different configurations.

This is why configuring `overrides` as the **primary** element of config is required.

In your setup above you have got a lot of things defined at the root of the config, and are then later applying overrides. This means that **all files, regardless of their type, are going to inherit the settings you have defined at the root of your config**, and then the `overrides` will apply on top.

Your specific error shows that this is problematic. In your root `rules` you are using `'import/no-deprecated': 'warn',` so this will apply to every file whether it is appropriate or not. And in the case of `.html` files it of course is not appropriate and it is throwing an error.

If you rearrange the configuration to only apply the TypeScript/code related rules to TypeScript files by including them in the relevant part of the `overrides` section instead of the root, things should work as expected.

I can see you are also making use of Nx - I am happy to say that I am collaborating with Nrwl and will land a major improvement PR hopefully next week on the ESLint story, which also includes these relevant changes out of the box with Nx: https://github.com/nrwl/nx/pull/3763

**Comment by manju-reddys** [comment]
Hi @JamesHenry , I did try playing to move configs as you suggested but none worked for me. Also moved all relevant overrides as well.

```
module.exports = {
   env: {
      browser: true,
      es6: true,
      node: true,
   },
   extends: [
      'prettier',
      'eslint:recommended',
      'plugin:@typescript-eslint/recommended',
      'plugin:prettier/recommended',
      'plugin:@angular-eslint/recommended',
      'plugin:import/typescript',
      'plugin:import/warnings',
      'plugin:import/errors',
   ],
   parser: '@typescript-eslint/parser',
   parserOptions: {
      project: './tsconfig.json',
      sourceType: 'module',
      ecmaVersion: 2020,
   },
   settings: {
      'import/resolver': {
         typescript: { alwaysTryTypes: true },
      },
   },
   plugins: [
      '@typescript-eslint',
      '@nrwl/eslint-plugin-nx',
      '@angular-eslint',
      'jest',
      'import',
   ],
   /**
    * -----------------------------------------------------
    * NOTES ON CONFIGURATION STRUCTURE ANGULAR SPECIFIC
    * -----------------------------------------------------
    *
    * Out of the box, ESLint does not support TypeScript or HTML. Naturally those are the two
    * main file types we care about in Angular projects, so we have to do a little extra work
    * to configure ESLint exactly how we need to.
    *
    * Fortunately, ESLint gives us an 'overrides' configuration option which allows us to set
    * different lint tooling (parser, plugins, rules etc) for different file types, which is
    * critical because our .ts files require a different parser and different rules to our
    * .html (and our inline Component) templates.
    */
   overrides: [
      /**
       * -----------------------------------------------------
       * TYPESCRIPT FILES (COMPONENTS, SERVICES ETC) (.ts)
       * -----------------------------------------------------
       */
      {
         files: ['*.ts'],
         /**
          * We use a dedicated tsconfig file for the compilation related to linting so that we
          * have complete control over what gets included and we can maximize performance
          */
         parserOptions: {
            project: './tsconfig.eslint.json',
            sourceType: 'module',
            ecmaVersion: 2020,
         },
         /**
          * See packages/eslint-plugin/src/configs/README.md
          * for what this recommended config contains.
          */
         extends: ['plugin:@angular-eslint/recommended'],
         rules: {
            /**
             * Any TypeScript related rules you wish to use/reconfigure over and above the
             * recommended set provided by the @angular-eslint project would go here.
             *
             * There are some examples below from the multiple plugins and ESLint core:
             */

            // ORIGINAL tslint.json -> 'directive-selector': [true, 'attribute', 'app', 'camelCase'],
            '@angular-eslint/directive-selector': [
               'error',
               { type: 'attribute', prefix: 'portals', style: 'camelCase' },
            ],

            // ORIGINAL tslint.json -> 'component-selector': [true, 'element', 'app', 'kebab-case'],
            '@angular-eslint/component-selector': [
               'error',
               { type: 'element', prefix: 'portals', style: 'kebab-case' },
            ],

            quotes: ['error', 'single', { allowTemplateLiterals: true }],
            '@typescript-eslint/no-misused-promises': ['error'],
            '@typescript-eslint/consistent-type-definitions': 'error',
            '@typescript-eslint/dot-notation': 'off',
            '@typescript-eslint/explicit-member-accessibility': [
               'off',
               {
                  accessibility: 'explicit',
               },
            ],
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/member-ordering': 'error',
            '@typescript-eslint/naming-convention': 'error',
            '@typescript-eslint/no-empty-function': 'off',
            '@typescript-eslint/no-empty-interface': 'error',
            '@typescript-eslint/no-inferrable-types': [
               'error',
               {
                  ignoreParameters: true,
               },
            ],
            '@typescript-eslint/no-misused-new': 'error',
            '@typescript-eslint/no-non-null-assertion': 'error',
            '@typescript-eslint/no-unused-expressions': 'error',
            '@typescript-eslint/prefer-function-type': 'error',
            '@typescript-eslint/unified-signatures': 'error',
            '@angular-eslint/no-conflicting-lifecycle': 'error',
            '@angular-eslint/no-host-metadata-property': 'error',
            '@angular-eslint/no-input-rename': 'error',
            '@angular-eslint/no-inputs-metadata-property': 'error',
            '@angular-eslint/no-output-native': 'error',
            '@angular-eslint/no-output-on-prefix': 'error',
            '@angular-eslint/no-output-rename': 'error',
            '@angular-eslint/no-outputs-metadata-property': 'error',
            '@angular-eslint/use-lifecycle-interface': 'error',
            '@angular-eslint/use-pipe-transform-interface': 'error',
            'import/no-deprecated': 'warn', // I moved this to rules section but didn't work either
         },
      },

      /**
       * -----------------------------------------------------
       * COMPONENT TEMPLATES
       * -----------------------------------------------------
       *
       * If you use inline templates, make sure you read the notes on the configuration
       * object after this one to understand how they relate to this configuration directly
       * below.
       */
      {
         files: ['*.component.html'],
         /**
          * See packages/eslint-plugin-template/src/configs/README.md
          * for what this recommended config contains.
          */
         extends: ['plugin:@angular-eslint/template/recommended'],
         rules: {
            /**
             * Any template/HTML related rules you wish to use/reconfigure over and above the
             * recommended set provided by the @angular-eslint project would go here.
             *
             * There is an example below from ESLint core (note, this specific example is not
             * necessarily recommended for all projects):
             */
            'max-len': ['error', { code: 140 }],
         },
      },

      /**
       * -----------------------------------------------------
       * EXTRACT INLINE TEMPLATES (from within .component.ts)
       * -----------------------------------------------------
       *
       * This extra piece of configuration is necessary to extract inline
       * templates from within Component metadata, e.g.:
       *
       * @Component({
       *  template: `<h1>Hello, World!</h1>`
       * })
       * ...
       *
       * It works by extracting the template part of the file and treating it as
       * if it were a full .html file, and it will therefore match the configuration
       * specific for *.component.html above when it comes to actual rules etc.
       *
       * NOTE: This processor will skip a lot of work when it runs if you don't use
       * inline templates in your projects currently, so there is no great benefit
       * in removing it, but you can if you want to.
       *
       * You won't specify any rules here. As noted above, the rules that are relevant
       * to inline templates are the same as the ones defined for *.component.html.
       */
      {
         files: ['*.component.ts'],
         extends: ['plugin:@angular-eslint/template/process-inline-templates'],
      },
   ],
   rules: {
      '@nrwl/nx/enforce-module-boundaries': [
         'error',
         {
            allow: [],
            depConstraints: [
               {
                  sourceTag: 'scope:api-interface',
                  onlyDependOnLibsWithTags: ['scope:api-interface'],
               },
               {
                  sourceTag: 'scope:utils',
                  onlyDependOnLibsWithTags: [
                     'scope:utils',
                     'scope:api-interface',
                  ],
               },
               {
                  sourceTag: 'scope:ui',
                  onlyDependOnLibsWithTags: [
                     'scope:ui',
                     'scope:utils',
                     'scope:api-interface',
                  ],
               },
               {
                  sourceTag: 'scope:nest',
                  onlyDependOnLibsWithTags: [
                     'scope:nest',
                     'scope:openid',
                     'scope:logger',
                     'scope:utils',
                     'scope:api-interface',
                  ],
               },
               {
                  sourceTag: 'scope:openid',
                  onlyDependOnLibsWithTags: [
                     'scope:openid',
                     'scope:logger',
                     'scope:utils',
                     'scope:api-interface',
                  ],
               },
               {
                  sourceTag: 'scope:logger',
                  onlyDependOnLibsWithTags: [
                     'scope:logger',
                     'scope:utils',
                     'scope:api-interface',
                  ],
               },
               {
                  sourceTag: 'scope:armadaserver',
                  onlyDependOnLibsWithTags: [
                     'scope:armadaserver',
                     'scope:nest',
                     'scope:api-interface',
                  ],
               },
               {
                  sourceTag: 'scope:monitoringingest',
                  onlyDependOnLibsWithTags: [
                     'scope:monitoringingest',
                     'scope:nest',
                     'scope:api-interface',
                  ],
               },
               {
                  sourceTag: 'scope:pdfserver',
                  onlyDependOnLibsWithTags: ['scope:pdfserver', 'scope:utils'],
               },
               {
                  sourceTag: 'scope:armadasync',
                  onlyDependOnLibsWithTags: [
                     'scope:armadasync',
                     'scope:utils',
                     'scope:api-interface',
                  ],
               },
               {
                  sourceTag: 'scope:armada',
                  onlyDependOnLibsWithTags: [
                     'scope:armada',
                     'scope:ui',
                     'scope:api-interface',
                  ],
               },
            ],
         },
      ],

      'import/no-deprecated': 'off',
      'arrow-body-style': 'error',
      'constructor-super': 'error',
      eqeqeq: ['error', 'smart'],
      'guard-for-in': 'error',
      'id-blacklist': 'off',
      'id-match': 'off',
      'no-bitwise': 'off',
      'no-caller': 'error',
      'no-console': [
         'error',
         {
            allow: [
               'log',
               'warn',
               'dir',
               'timeLog',
               'assert',
               'clear',
               'count',
               'countReset',
               'group',
               'groupEnd',
               'table',
               'dirxml',
               'error',
               'groupCollapsed',
               'Console',
               'profile',
               'profileEnd',
               'timeStamp',
               'context',
            ],
         },
      ],
      'no-debugger': 'error',
      'no-empty': 'off',
      'no-eval': 'error',
      'no-fallthrough': 'error',
      'no-new-wrappers': 'error',
      'no-restricted-imports': ['error', 'rxjs/Rx'],
      'no-shadow': [
         'error',
         {
            hoist: 'all',
         },
      ],
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'off',
      'no-var': 'error',
      'prefer-const': 'error',
      radix: 'error',
   },
};
```

**Comment by manju-reddys** [comment]
Additional note: most of the configuration was generated by the angular eslint schematic.

**Comment by JamesHenry** [comment]
Hi @manju-reddys you still have all of this going on at the root of the config:

```env: {
      browser: true,
      es6: true,
      node: true,
   },
   extends: [
      'prettier',
      'eslint:recommended',
      'plugin:@typescript-eslint/recommended',
      'plugin:prettier/recommended',
      'plugin:@angular-eslint/recommended',
      'plugin:import/typescript',
      'plugin:import/warnings',
      'plugin:import/errors',
   ],
   parser: '@typescript-eslint/parser',
   parserOptions: {
      project: './tsconfig.json',
      sourceType: 'module',
      ecmaVersion: 2020,
   },
   settings: {
      'import/resolver': {
         typescript: { alwaysTryTypes: true },
      },
   },
   plugins: [
      '@typescript-eslint',
      '@nrwl/eslint-plugin-nx',
      '@angular-eslint',
      'jest',
      'import',
   ],```

That's what I was saying had to be rearchitected. You need to apply those things within the overrides.

Currently, by having the `parser` and all those `extends` from different configs at the root, they apply to EVERY file that gets linted. That is not what we want in an Angular context, because .ts and .html are so different and require different parsers and rules to apply to them.

Hope that helps
