### ISSUE TITLE
Conflict with standard plugin

### ISSUE THREAD

**Issue by ltvan** [angular-eslint/angular-eslint#1615]
Issue: The `@angular-eslint/eslint-plugin-template` is conflict with `standard` plugin and cause the linting to failed with exception.

The issue can be reproduced using this repo:
https://github.com/ltvan/angular-eslint-conflict

Run `yarn lint` on master => error:
```
TypeError: programNode.body is not iterable
Occurred while linting ./src/app/app.component.html:2
Rule: "n/no-deprecated-api"
    at ReferenceTracker.iterateEsmReferences (./node_modules/@eslint-community/eslint-utils/index.js:1689:40)
    at iterateEsmReferences.next (<anonymous>)
    at Program:exit (./node_modules/eslint-plugin-n/lib/rules/no-deprecated-api.js:775:32)
    at ruleErrorHandler (./node_modules/eslint/lib/linter/linter.js:1091:28)
    at ./node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (./node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (./node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (./node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.leaveNode (./node_modules/eslint/lib/linter/node-event-generator.js:349:14)
```

If we either remove the `standard` from `extends` clause, or remove the `plugin:@angular-eslint/template/recommended` from the override bellow, the linting is successful (with linting error as expected).

If we remove the `prettier` (or rollback to the previous commit, which is no prettier included yet), the same bug but with a bit different error:

```
TypeError: Cannot read properties of undefined (reading '0')
Occurred while linting ./src/app/app.component.html:2
Rule: "indent"
    at SourceCode.getFirstToken (./node_modules/eslint/lib/source-code/token-store/index.js:261:23)
    at addToIgnoredNodes (./node_modules/eslint/lib/rules/indent.js:1685:51)
    at *:exit (./node_modules/eslint/lib/rules/indent.js:1709:25)
    at ruleErrorHandler (./node_modules/eslint/lib/linter/linter.js:1091:28)
    at ./node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (./node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (./node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (./node_modules/eslint/lib/linter/node-event-generator.js:324:22)
    at NodeEventGenerator.leaveNode (./node_modules/eslint/lib/linter/node-event-generator.js:349:14)
```

I also tried to downgrade to `standard@16` and `eslint@7` (and corresponding versions for standard related packages) but the issue still there.

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `16.0.3` |
| `@angular-eslint/template-parser`         | `16.0.3` |
| `@typescript-eslint/parser`               | `5.62.0` |
| `ESLint`                                  | `8.53.0` |
| `node`                                    | `18.12.1` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 16.2.10
Node: 18.12.1
Package Manager: yarn 1.22.19
OS: darwin x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3

```
- [ x] I have tried restarting my IDE and the issue persists.
- [x ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
@ltvan How to apply things to your configuration in the context of angular-eslint is documented at length in the README.

https://github.com/angular-eslint/angular-eslint#notes-on-eslint-configuration-itself

Emphasised particularly in this section:

<img width="939" alt="image" src="https://github.com/angular-eslint/angular-eslint/assets/900523/f717cc56-8b68-49fb-af46-7aae2354013a">

The solution is to follow that guidance in the README:

<img width="608" alt="image" src="https://github.com/angular-eslint/angular-eslint/assets/900523/8fb3168b-8163-4955-9fe5-638c38517cc8">

**ONLY** things which apply to absolutely every type of file you are linting can go at the top level, everything else needs to be in appropriate overrides
