### ISSUE TITLE
multi-line inline-templates with CRLF line endings

### ISSUE THREAD

**Issue by jr01** [angular-eslint/angular-eslint#185]
Linting fails on component files that have CRLF (eg. Windows) line endings.

Same issue as https://github.com/angular-eslint/angular-eslint/issues/162, but now with steps to reproduce (on Linux):
```
git clone https://github.com/angular-eslint/angular-eslint
cd angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config
npm install
ng add @angular-eslint/schematics
unix2dos src/app/example.component.ts
ng lint v1014-multi-project-manual-config
```

Shows error
```
Linting "v1014-multi-project-manual-config"...
Error: Debug Failure. False expression: position cannot precede the beginning of the file
    at computeLineOfPosition (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/typescript/lib/typescript.js:8934:22)
    at computeLineAndCharacterOfPosition (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/typescript/lib/typescript.js:8912:26)
    at Object.getLineAndCharacterOfPosition (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/typescript/lib/typescript.js:8953:16)
    at SourceFileObject.getLineAndCharacterOfPosition (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/typescript/lib/typescript.js:143364:23)
    at preprocess (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/@angular-eslint/eslint-plugin-template/dist/index.js:1:1430)
    at Linter._verifyWithProcessor (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/eslint/lib/linter/linter.js:1292:30)
    at Linter._verifyWithConfigArray (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/eslint/lib/linter/linter.js:1264:25)
    at Linter.verify (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/eslint/lib/linter/linter.js:1226:25)
    at Linter.verifyAndFix (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/eslint/lib/linter/linter.js:1416:29)
    at verifyText (/home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/node_modules/eslint/lib/cli-engine/cli-engine.js:239:48)
preprocess: ERROR could not parse @Component() metadata /home/me/repos/angular-eslint/packages/integration-tests/fixtures/v1014-multi-project-manual-config/src/app/example.component.ts
```

Workaround: change line endings to LF, eg. using dos2unix, or notepad++.

**Comment by jr01** [comment]
@JamesHenry - This test reproduces the error -- notice the `\r\n` at each line end. The fix below fixes . Well at least it fixes the test...I haven't been able to compile the full source yet and run `ng lint` with it, so I'm not sure if this is a true fix....

Testcase:
```
 describe('components with inline templates and CRLF', () => {
      let inlineTemplate = `\r\n
        <div [style.height]="aBool ? '100px' : '200px'"></div>\r\n
        <div [style]="{height: this.aBool ? '100px' : '200px'}"></div>\r\n
        <div [style]="{height: '100px'}"></div>\r\n
      `;

      const testCases = [
        {
          input: `
            import {Component} from '@angular/core';\r\n
\r\n
            @Component({\r\n
              selector: 'app-root',\r\n
              template: \`${inlineTemplate}\`,\r\n
              styleUrls: ['./app.component.scss']\r\n
            })\r\n
            export class AppComponent {\r\n
              public aBool = false;\r\n
              public aStyle = {height: this.aBool ? '100px' : '200px'};\r\n
            }\r\n
        `,
        },
      ];

      testCases.forEach((tc, i) => {
        it(`should extract the inline HTML of components with inline templates, CASE: ${i}`, () => {
          expect(
            processors['extract-inline-html'].preprocess(
              tc.input,
              'test.component.ts',
            ),
          ).toEqual([
            tc.input,
            {
              filename: 'inline-template-1.component.html',
              text: inlineTemplate.replace(/\r\n/g, '\n'),
            },
          ]);
        });
      });
    });
```

Fix
```
function quickGetRangeForTemplate(text: string, template: string) {
  text = text.replace(/\r\n/g, '\n');
  const start = text.indexOf(template);
  return [start, start + template.length];
}
```

**Comment by woppa684** [comment]
Same issue for us indeed, making a one-liner of the template, changing the line endings to UNIX or putting the template in a separate file fixes it.

**Comment by JamesHenry** [comment]
Ok this makes sense I think.

@jr01 Please could you submit your work as a PR? 

> I haven't been able to compile the full source yet

I'm not sure what you mean by this
