### ISSUE TITLE
Eslint cache is not working with processInlineTemplates

### ISSUE THREAD

**Issue by kryshac** [angular-eslint/angular-eslint#1917]
**Description and reproduction of the issue**

when i use `processInlineTemplates` cache it stops working:

```sh
❯ ./node_modules/.bin/eslint --cache --cache-strategy content ./

Oops! Something went wrong! :(

ESLint: 9.6.0

Error: Could not serialize processor object (missing 'meta' object).
    at Object.value (/home/user/work/angular/app/node_modules/eslint/lib/config/flat-config-array.js:390:27)
    at stringify (/home/user/work/angular/app/node_modules/json-stable-stringify-without-jsonify/index.js:25:25)
    at module.exports (/home/user/work/angular/app/node_modules/json-stable-stringify-without-jsonify/index.js:68:7)
    at hashOfConfigFor (/home/user/work/angular/app/node_modules/eslint/lib/cli-engine/lint-result-cache.js:50:75)
    at LintResultCache.getCachedLintResults (/home/user/work/angular/app/node_modules/eslint/lib/cli-engine/lint-result-cache.js:116:30)
    at /home/user/work/angular/app/node_modules/eslint/lib/eslint/eslint.js:903:41
    at Array.map (<anonymous>)
    at ESLint.lintFiles (/home/user/work/angular/app/node_modules/eslint/lib/eslint/eslint.js:882:23)
    at async Object.execute (/home/user/work/angular/app/node_modules/eslint/lib/cli.js:521:23)
    at async main (/home/user/work/angular/app/node_modules/eslint/bin/eslint.js:153:22)

```

```js
{
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      ...tseslint.recommended,
      ...tseslint.stylistic,
      ...angular.tsRecommended
    ],
    processor: processInlineTemplates
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `18.0.0-alpha.16` |
| `@typescript-eslint/parser`        | `8.0.0-alpha.20` |
| `ESLint`                           | `9.6.0` |
| `node`                             | `20.15.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 18.0.7
Node: 20.15.0
Package Manager: npm 10.7.0
OS: linux x64

Angular: 18.0.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.7
@angular-devkit/build-angular   18.0.7
@angular-devkit/core            18.0.7
@angular-devkit/schematics      18.0.7
@angular/cli                    18.0.7
@schematics/angular             18.0.7
ng-packagr                      18.0.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7

```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by yangxiaolang** [comment]
It looks like this Issue is related to your problem https://github.com/eslint/eslint/issues/18689
I've temporarily handled this with `patch-package`
```javascript
// node_modules/@angular-eslint/eslint-plugin-template/dist/processors.js
exports.default = {
    'extract-inline-html': {
        meta:{
            name:'extract-inline-html',
        },
        preprocess: preprocessComponentFile,
        postprocess: postprocessComponentFile,
        supportsAutofix: true,
    },
};
```
