### ISSUE TITLE
Error asking to provide "parserOptions.project", yet it is already defined in my .eslintrc.js file

### ISSUE THREAD

**Issue by TheTylerHuskins** [angular-eslint/angular-eslint#354]
I am attempting to move my project from TSLint to ESLint, but I keep running into this problem. When running the command `eslint -c .eslintrc.js --ext .ts,.html .` I get this error

```
Oops! Something went wrong! :(

ESLint: 7.21.0

Error: Error while loading rule '@typescript-eslint/dot-notation': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for 
@typescript-eslint/parser.
Occurred while linting C:\sources\TELeO\TELEscrow\ClientApp\app\app.browser.module.ts
    at Object.getParserServices (C:\sources\TELeO\TELEscrow\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\getParserServices.js:16:15)
    at create (C:\sources\TELeO\TELEscrow\node_modules\@typescript-eslint\eslint-plugin\dist\rules\dot-notation.js:78:39)
    at Object.create (C:\sources\TELeO\TELEscrow\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\RuleCreator.js:13:24)
    at createRuleListeners (C:\sources\TELeO\TELEscrow\node_modules\eslint\lib\linter\linter.js:761:21)
    at C:\sources\TELeO\TELEscrow\node_modules\eslint\lib\linter\linter.js:931:31
    at Array.forEach (<anonymous>)
    at runRules (C:\sources\TELeO\TELEscrow\node_modules\eslint\lib\linter\linter.js:876:34)
    at Linter._verifyWithoutProcessors (C:\sources\TELeO\TELEscrow\node_modules\eslint\lib\linter\linter.js:1175:31)
    at Linter._verifyWithConfigArray (C:\sources\TELeO\TELEscrow\node_modules\eslint\lib\linter\linter.js:1273:21)
    at Linter.verify (C:\sources\TELeO\TELEscrow\node_modules\eslint\lib\linter\linter.js:1228:25) 
```
This would lead one to believe that the `parserOptions.project` property is  not defined. Plot twist, it IS defined and always has been. 

```
module.exports = {
  parser: "@angular-eslint/template-parser",
  parserOptions: {
    project: './tsconfig.json',
    sourceType: "module"
  },
  "env": {
    "browser": true,
    "node": true
  },
  "extends": [
    "prettier"
  ],
  "plugins": [
    "eslint-plugin-import",
    "eslint-plugin-unicorn",
    "eslint-plugin-no-null",
    "@angular-eslint/eslint-plugin",
    "@angular-eslint/eslint-plugin-template",
    "@typescript-eslint"
  ],
  ...
}
```

I am not sure where I should go from here...

**Comment by JamesHenry** [comment]
Please take a look at the Notes on ESLint configuration section of the README: https://github.com/angular-eslint/angular-eslint#notes-on-eslint-configuration

It covers the “why” behind the issue you have above.

Hopefully it’s just the case that you haven’t seen these docs, but please let me know if any of it is unclear.

**Comment by JamesHenry** [comment]
I will definitely help you directly if it’s still unclear after reading but I want to try and help people help themselves with these docs so that it scales better

**Comment by TheTylerHuskins** [comment]
Thank you for pointing me in the right direction James. I followed the documentation, and it works (imagine that)!

**Comment by JamesHenry** [comment]
Ok great @TheTylerHuskins, thanks for confirming 👍
