### ISSUE TITLE
unclear path from error during upgrade of angular 10

### ISSUE THREAD

**Issue by robbiemu** [angular-eslint/angular-eslint#409]
I am on angular 10.2, and needing to upgrade from tslint.

So I thought to follow the steps:

```bash
npm i -D @angular-eslint/schematics
ng g @angular-eslint/schematics:convert-tslint-to-eslint my_project
```
the second cannot be run first. the first produces:
```none
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cli@">= 11.2.0 < 12.0.0" from @angular-eslint/schematics@2.1.0
```

**Comment by turbolego** [comment]
I have the same issue:

```
ng add @angular-eslint/schematics
Skipping installation: Package already installed

    All @angular-eslint dependencies have been successfully installed �

    Please see https://github.com/angular-eslint/angular-eslint for how to add ESLint configuration to your project.

UPDATE package.json (3626 bytes)
/ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.0.0
npm ERR! Found: @angular/compiler@11.0.2
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"11.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@">= 11.2.0 < 12.0.0" from @angular-eslint/eslint-plugin@4.2.0
npm ERR! node_modules/@angular-eslint/eslint-plugin
npm ERR!   dev @angular-eslint/eslint-plugin@"4.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\toband\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\toband\AppData\Local\npm-cache\_logs\2021-05-06T09_52_36_715Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.
```

logfile:
```
0 verbose cli [
0 verbose cli   'C:\\DATA\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\toband\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '@angular/compiler@latest',
0 verbose cli   '--save-dev'
0 verbose cli ]
1 info using npm@7.11.2
2 info using node@v12.18.0
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\toband\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\DATA\IdeaProjects\labsys\frontend\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\toband\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\toband\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 20ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree:init Completed in 1087ms
29 timing arborist:ctor Completed in 0ms
30 http fetch GET 304 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/@angular%2fcompiler 1132ms
31 timing idealTree:userRequests Completed in 1155ms
32 silly idealTree buildDeps
33 silly fetch manifest @angular-eslint/builder@4.2.0
34 http fetch GET 200 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/@angular-eslint%2fbuilder 98ms
35 silly fetch manifest @angular/cli@^11.2.11
36 http fetch GET 304 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/@angular%2fcli 143ms
37 silly fetch manifest eslint@^7.6.0
38 http fetch GET 200 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/eslint 142ms
39 silly fetch manifest typescript@4.0.5
40 http fetch GET 304 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/typescript 364ms
41 silly fetch manifest @angular-eslint/eslint-plugin@4.2.0
42 http fetch GET 304 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/@angular-eslint%2feslint-plugin 81ms
43 silly fetch manifest @angular/compiler@11.2.12
44 silly fetch manifest @angular-eslint/eslint-plugin-template@4.2.0
45 http fetch GET 200 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/@angular-eslint%2feslint-plugin-template 87ms
46 silly fetch manifest @angular-eslint/template-parser@4.2.0
47 http fetch GET 200 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/@angular-eslint%2ftemplate-parser 98ms
48 silly fetch manifest @typescript-eslint/eslint-plugin@4.16.1
49 http fetch GET 200 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/@typescript-eslint%2feslint-plugin 1614ms
50 silly fetch manifest @typescript-eslint/parser@4.16.1
51 http fetch GET 200 https://artrepo.vegvesen.no/artifactory/api/npm/npm-all/@typescript-eslint%2fparser 634ms
52 silly placeDep ROOT @angular-eslint/builder@4.2.0 OK for: frontend@0.0.0 want: 4.2.0
53 timing idealTree Completed in 6190ms
54 timing command:install Completed in 6202ms
55 verbose stack Error: unable to resolve dependency tree
55 verbose stack     at Arborist.[failPeerConflict] (C:\Users\toband\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1221:25)
55 verbose stack     at Arborist.[placeDep] (C:\Users\toband\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1324:32)
55 verbose stack     at C:\Users\toband\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:905:46
55 verbose stack     at Array.map (<anonymous>)
55 verbose stack     at Arborist.[buildDepStep] (C:\Users\toband\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:905:8)
55 verbose stack     at async Arborist.buildIdealTree (C:\Users\toband\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:218:7)
55 verbose stack     at async Promise.all (index 1)
55 verbose stack     at async Arborist.reify (C:\Users\toband\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:135:5)
55 verbose stack     at async Install.install (C:\Users\toband\AppData\Roaming\npm\node_modules\npm\lib\install.js:137:5)
56 verbose cwd C:\DATA\IdeaProjects\labsys\frontend
57 verbose Windows_NT 10.0.18363
58 verbose argv "C:\\DATA\\nodejs\\node.exe" "C:\\Users\\toband\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@angular/compiler@latest" "--save-dev"
59 verbose node v12.18.0
60 verbose npm  v7.11.2
61 error code ERESOLVE
62 error ERESOLVE unable to resolve dependency tree
63 error
64 error Found: [1m@angular/compiler[22m@[1m11.0.2[22m[2m[22m
64 error [2mnode_modules/@angular/compiler[22m
64 error   [35mpeer[39m [1m@angular/compiler[22m@"[1m11.0.2[22m" from [1m@angular/compiler-cli[22m@[1m11.0.2[22m[2m[22m
64 error   [2mnode_modules/@angular/compiler-cli[22m
64 error     [35mpeer[39m [1m@angular/compiler-cli[22m@"[1m^11.0.0 || ^11.2.0-next[22m" from [1m@angular-devkit/build-angular[22m@[1m0.1102.11[22m[2m[22m
64 error     [2mnode_modules/@angular-devkit/build-angular[22m
64 error       [33mdev[39m [1m@angular-devkit/build-angular[22m@"[1m^0.1102.11[22m" from the root project
64 error     [35mpeer[39m [1m@angular/compiler-cli[22m@"[1m^11.0.0 || ^11.2.0-next[22m" from [1m@ngtools/webpack[22m@[1m11.2.11[22m[2m[22m
64 error     [2mnode_modules/@ngtools/webpack[22m
64 error       [1m@ngtools/webpack[22m@"[1m11.2.11[22m" from [1m@angular-devkit/build-angular[22m@[1m0.1102.11[22m[2m[22m
64 error       [2mnode_modules/@angular-devkit/build-angular[22m
64 error         [33mdev[39m [1m@angular-devkit/build-angular[22m@"[1m^0.1102.11[22m" from the root project
64 error     1 more (the root project)
64 error   [35mpeer[39m [1m@angular/compiler[22m@"[1m11.0.2[22m" from [1m@angular/platform-browser-dynamic[22m@[1m11.0.2[22m[2m[22m
64 error   [2mnode_modules/@angular/platform-browser-dynamic[22m
64 error     [1m@angular/platform-browser-dynamic[22m@"[1m11.0.2[22m" from the root project
64 error   1 more (the root project)
64 error
64 error Could not resolve dependency:
64 error [33mdev[39m [1m@angular-eslint/eslint-plugin[22m@"[1m4.2.0[22m" from the root project
64 error
64 error Conflicting peer dependency: [1m@angular/compiler[22m@[1m11.2.12[22m[2m[22m
64 error [2mnode_modules/@angular/compiler[22m
64 error   [35mpeer[39m [1m@angular/compiler[22m@"[1m>= 11.2.0 < 12.0.0[22m" from [1m@angular-eslint/eslint-plugin[22m@[1m4.2.0[22m[2m[22m
64 error   [2mnode_modules/@angular-eslint/eslint-plugin[22m
64 error     [33mdev[39m [1m@angular-eslint/eslint-plugin[22m@"[1m4.2.0[22m" from the root project
64 error
64 error Fix the upstream dependency conflict, or retry
64 error this command with --force, or --legacy-peer-deps
64 error to accept an incorrect (and potentially broken) dependency resolution.
64 error
64 error See C:\Users\toband\AppData\Local\npm-cache\eresolve-report.txt for a full report.
65 verbose exit 1
```

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.11
Node: 12.18.0
OS: win32 x64

Angular: 11.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.11
@angular-devkit/build-angular   0.1102.11
@angular-devkit/core            11.2.11
@angular-devkit/schematics      11.2.11
@angular/cdk                    11.2.11
@angular/cli                    11.2.11
@angular/material               11.2.11
@schematics/angular             11.2.11
@schematics/update              0.1102.11
rxjs                            6.6.3
typescript                      4.0.5
webpack                         4.39.2
```
