### ISSUE TITLE
Unable to use @angular-eslint/schematics:ng-add due to schema validation error

### ISSUE THREAD

**Issue by GreG28** [angular-eslint/angular-eslint#578]
Hi guys, 

I'm trying to make a custom Angular Schematic using your schematics to manipulate my projects and applying other changes of my own. But anytime I try using your '@angular-eslint/schematics:ng-add' as an externalSchematic I bump into en error of schema validation of Angular. 

I'm producing a code looking like the following.
```typescript
return (host: Tree, context: SchematicContext) => {
        const projectPackageJSON = (host.read('package.json') as Buffer).toString(
            'utf-8',
        );
        const json = JSON.parse(projectPackageJSON);
        json.devDependencies = json.devDependencies || {};
        json.devDependencies['@angular-eslint/schematics'] = '12.0.0';
        json.devDependencies = sortObjectByKeys(json.devDependencies);
        host.overwrite('package.json', JSON.stringify(json, null, 2));

        const task1 = context.addTask(new NodePackageInstallTask({quiet: false, hideOutput: false}));

        context.addTask(new RunSchematicTask(
            '@angular-eslint/schematics',
            'ng-add',
            '',
        ), [task1]);

        return host;
    }
````

The error I'm getting while attempting to use It. 
```
Error: Schematic input does not validate against the Schema: ""
Errors:

  Data path "" must be object.
    at MapSubscriber.project (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/home/meteojob/.nvm/versions/node/v12.18.3/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
```

I was wondering if It had to do with your schema.json containing empty nodes for 'properties' and 'required'. Could we just not add those entries in the schema ?

Thanks for your help!

Ps: Sorry for my english :/

**Comment by GreG28** [comment]
Sorry I misunderstood the usage of options while empty.
