### ISSUE TITLE
Crash when running ng lint

### ISSUE THREAD

**Issue by dieend** [angular-eslint/angular-eslint#60]
version: "0.0.1-alpha.23"

```
> cat /private/var/folders/qx/l6dzbht15fj_s89bxrv7x7740000gp/T/ng-JaEvnr/angular-errors.log

[error] TypeError: Cannot read property 'range' of undefined
    at /path/to/angular_project/node_modules/@angular-eslint/eslint-plugin-template/dist/index.js:1:1353
    at Array.map (<anonymous>)
    at postprocess (/path/to/angular_project/node_modules/@angular-eslint/eslint-plugin-template/dist/index.js:1:1156)
    at Linter._verifyWithProcessor (/path/to/angular_project/node_modules/eslint/lib/linter/linter.js:1311:16)
    at Linter._verifyWithConfigArray (/path/to/angular_project/node_modules/eslint/lib/linter/linter.js:1248:25)
    at Linter.verify (/path/to/angular_project/node_modules/eslint/lib/linter/linter.js:1210:25)
    at Linter.verifyAndFix (/path/to/angular_project/node_modules/eslint/lib/linter/linter.js:1400:29)
    at verifyText (/path/to/angular_project/node_modules/eslint/lib/cli-engine/cli-engine.js:230:48)
    at CLIEngine.executeOnFiles (/path/to/angular_project/node_modules/eslint/lib/cli-engine/cli-engine.js:798:28)
    at _lint (/path/to/angular_project/node_modules/@angular-eslint/builder/dist/index.js:1:4477)
```

**Comment by paulotokimatu** [comment]
Hello, I tried to do a quick reproduction but didn't get this error. Can you please give us more details like the Angular version, the content of `.eslintrc.js` (or equivalent) and `angular.json`?

Thanks.

**Comment by dieend** [comment]
Hi, this crash was happened when I included the following config in eslintrc.js (copied from https://github.com/angular-eslint/angular-eslint/blob/master/packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.js)
```
{
    override: [
        ....
        {
            files: ['*.component.ts'],
            parser: '@typescript-eslint/parser',
            parserOptions: {
                ecmaVersion: 2020,
                sourceType: 'module',
            },
            plugins: ['@angular-eslint/template'],
            processor: '@angular-eslint/template/extract-inline-html',
        },
    ]
}
```
I'm unable to reproduce it right now because whenever I run `ng lint` with this configuration, it never completed (seems like in infinite loop/recursion or something)

**Comment by paulotokimatu** [comment]
Hmm ok, so from my understanding, what probably happened is that you didn't add the parser for .html files on your config like this:
https://github.com/angular-eslint/angular-eslint/blob/master/packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.js#L186

What happens is that `eslint-plugin-template` creates a temp file called `inline-template.component.html` (note the it ends with `component.html`) and then uses `template-parser` to parse it. If you don't add this part on the configuration the parsing will fail. Note that the actual linting rules for the template are set on this section.

Please @JamesHenry  correct me if I am wrong.

**Comment by dieend** [comment]
I did include the html override. My lint failed if I don't include that part.

**Comment by JamesHenry** [comment]
@dieend Please help me to help you... There is not enough information to debug this.

Clearly there is not a _general_ issue, otherwise the integration test would fail. Therefore, you are experiencing a specific issue, and debug a specific issue we will need more specific information. A small snippet from an ESLint config is not enough.

Please provide as much information as possible, and ideally a reproduction we can execute.

Thanks!

**Comment by digeomel** [comment]
I'm getting a similar error, eslint crashes on a component template. This is my .eslintrc.js:

```
// https://github.com/angular/angular-cli/issues/13732
// https://github.com/angular-eslint/angular-eslint
// https://github.com/angular-eslint/angular-eslint/blob/master/packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.js
// https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration

module.exports = {
    "env": {
        "browser": true,
        "node": true
    },
    "overrides": [
        {
            "files": ["*.ts"],
            "parser": "@typescript-eslint/parser",
            "parserOptions": {
                "project": "tsconfig.json",
                "sourceType": "module",
                "ecmaVersion": 2020
            },
            "plugins": [
                "@typescript-eslint",
                "@angular-eslint",
                "import"
//              "deprecate"
            ],
            "rules": {
                // angular-eslint [start]
                "@typescript-eslint/array-type": "off",
                "arrow-parens": "off",
                "@angular-eslint/component-class-suffix": "error",
                "@angular-eslint/contextual-lifecycle": "error",
                "@angular-eslint/directive-selector": [
                    "error",
                    { type: "attribute", prefix: "agora", style: "camelCase" }
                ],
                "@angular-eslint/component-selector": [
                    "error",
                    { type: "element", prefix: "agora", style: "kebab-case" }
                ],        
                "@typescript-eslint/interface-name-prefix": "off",
                "max-classes-per-file": "off",
                "@typescript-eslint/member-ordering": [
                    "error",
                    {
                        default: [
                            "static-field",
                            "instance-field",
                            "static-method",
                            "instance-method",
                        ]
                    }
                ],
                "no-multiple-empty-lines": "off",
                "no-restricted-syntax": [
                    "error",
                    {
                        selector: "CallExpression[callee.object.name=\"console\"][callee.property.name=/^(debug|info|time|timeEnd|trace)$/]",
                        message: "Unexpected property on console object was called"
                    }
                ],
                "@typescript-eslint/no-inferrable-types": [
                    "error",
                    {
                        ignoreParameters: true
                    }
                ],        
                "@typescript-eslint/no-var-requires": "off",
                "quote-props": ["error", "as-needed"],
                "sort-keys": "off",
                "comma-dangle": "off",
                "@angular-eslint/no-conflicting-lifecycle": "error",
                "@angular-eslint/no-host-metadata-property": "error",
                "@angular-eslint/no-input-rename": "error",
                "@angular-eslint/no-inputs-metadata-property": "error",
                "@angular-eslint/no-output-native": "error",
                "@angular-eslint/no-output-on-prefix": "error",
                "@angular-eslint/no-output-rename": "error",
                "@angular-eslint/no-outputs-metadata-property": "error",
                "@angular-eslint/use-lifecycle-interface": "warn",
                "@angular-eslint/use-pipe-transform-interface": "error",
                // angular-eslint [end]
                "@typescript-eslint/class-name-casing": "error",
                "@typescript-eslint/consistent-type-definitions": "error",
                "@typescript-eslint/explicit-member-accessibility": [
                    "off",
                    {
                        "accessibility": "explicit"
                    }
                ],
                "@typescript-eslint/indent": [
                    "warn",
                    4,
                    {
                        "ignoreComments": true,
                        "ignoredNodes": ["TSTypeParameterInstantiation"],
                        "SwitchCase": 1,
                        "VariableDeclarator": 1,
                        "MemberExpression": 1,
                        "FunctionDeclaration": { "body": 1, "parameters": 1 },
                        "FunctionExpression":  { "body": 1, "parameters": 1 },
                        "ArrayExpression": 1,
                        "ObjectExpression": 1,
                        "ImportDeclaration": 1
                    }
                ],
                "@typescript-eslint/member-delimiter-style": [
                    "warn",
                    {
                        "multiline": {
                            "delimiter": "semi",
                            "requireLast": true
                        },
                        "singleline": {
                            "delimiter": "semi",
                            "requireLast": false
                        }
                    }
                ],
                "@typescript-eslint/no-empty-function": "off",
                "@typescript-eslint/no-empty-interface": "error",
                "@typescript-eslint/no-misused-new": "error",
                "@typescript-eslint/no-non-null-assertion": "error",
                "@typescript-eslint/prefer-function-type": "error",
                "@typescript-eslint/quotes": [
                    "warn",
                    "single"
                ],
                "@typescript-eslint/semi": [
                    "warn",
                    "always"
                ],
                "@typescript-eslint/type-annotation-spacing": "error",
                "@typescript-eslint/unified-signatures": "error",
                "arrow-body-style": "warn",
                "camelcase": "off",
                "constructor-super": "error",
                "curly": "error",
                "dot-notation": "off",
                "eol-last": "warn",
                "eqeqeq": [
                    "error",
                    "smart"
                ],
                "guard-for-in": "error",
                "id-blacklist": "off",
                "id-match": "off",
                "import/no-deprecated": "warn",
//              "deprecate/function": "warn",
//              "deprecate/import": "warn",
//              "deprecate/member-expression": "warn",
                "max-len": [
                    "error",
                    {
                        "ignoreRegExpLiterals": false,
                        "ignorePattern": "^import .*",
                        "code": 140
                    }
                ],
                "no-bitwise": "error",
                "no-caller": "error",
                "no-console": [
                    "error",
                    {
                        "allow": [
                            "log",
                            "dirxml",
                            "warn",
                            "error",
                            "dir",
                            "timeLog",
                            "assert",
                            "clear",
                            "count",
                            "countReset",
                            "group",
                            "groupCollapsed",
                            "groupEnd",
                            "table",
                            "Console",
                            "markTimeline",
                            "profile",
                            "profileEnd",
                            "timeline",
                            "timelineEnd",
                            "timeStamp",
                            "context"
                        ]
                    }
                ],
                "no-debugger": "error",
                "no-empty": "off",
                "no-eval": "error",
                "no-fallthrough": "error",
                "no-new-wrappers": "error",
                "no-restricted-imports": [
                    "error",
                    {
                        paths: [
                            {
                                name: "rxjs/Rx",
                                message: "Please import directly from 'rxjs' instead",
                            },
                        ],
                    }
                ],
                "no-shadow": [
                    "error",
                    {
                        "hoist": "all"
                    }
                ],
                "no-throw-literal": "error",
                "no-trailing-spaces": "warn",
                "no-undef-init": "error",
                "no-underscore-dangle": "off",
                "no-unused-expressions": "error",
                "no-unused-labels": "error",
                "no-var": "error",
                "prefer-const": "warn",
                "radix": "error",
                "spaced-comment": "error"
/*                
                "@typescript-eslint/tslint/config": [
                    "error",
                    {
                        "rules": {
                            "component-class-suffix": true,
                            "directive-class-suffix": true,
                            "import-spacing": true,
                            "no-host-metadata-property": true,
                            "no-input-rename": true,
                            "no-inputs-metadata-property": true,
                            "no-output-on-prefix": true,
                            "no-output-rename": true,
                            "no-outputs-metadata-property": true,
                            "one-line": [
                                true,
                                "check-open-brace",
                                "check-catch",
                                "check-else",
                                "check-whitespace"
                            ],
                            "use-life-cycle-interface": true,
                            "use-pipe-transform-interface": true,
                            "whitespace": [
                                true,
                                "check-branch",
                                "check-decl",
                                "check-operator",
                                "check-separator",
                                "check-type"
                            ]
                        }
                    }
                ]
*/                
            }
        },
        {
            files: ["*.component.html"],
            parser: "@angular-eslint/template-parser",
            plugins: ["@angular-eslint/template"],
            rules: {
                "@angular-eslint/template/banana-in-a-box": "error",
                "@angular-eslint/template/no-negated-async": "error",
            }
        }
    ]
};

```

**Comment by Delagen** [comment]
Seems it stuck when parsing in CI. Removed *.html from lint glob, and all passed

**Comment by LouisSung** [comment]
@paulotokimatu @JamesHenry 
I can help on confirm this by providing some simple examples

Screen recording as shown below (1080p @[Here](https://user-images.githubusercontent.com/37973545/79011419-94cd1300-7b96-11ea-9982-5a93ac45a6bb.gif))
<img src="https://user-images.githubusercontent.com/37973545/79011401-88e15100-7b96-11ea-9360-19e791139fab.gif" width="600px">

---
This is my sample code
* **Pass**
  1. `<div [style.height]="'100px'"></div>`
  2. `<div [style]="aStyle"></div>`
* **Error**
  1. `<div [style.height]="aBool ? '100px' : '200px'"></div>`
  2. `<div [style]="{height: this.aBool ? '100px' : '200px'}"></div>`
  3. `<div [style]="{height: '100px'}"></div>`
```typescript
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  template: `<div></div>`,
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  public aBool = false;
  public aStyle = {height: this.aBool ? '100px' : '200px'};
}
```

**Comment by paulotokimatu** [comment]
Thanks a lot for the detailed report! I did a quick investigation and looks like the issue happens due to ":".

During the pre-processing of eslint-plugin-template the component decorator is parsed and the ":" is making the output of the parsing incomplete, triggering future errors.

The fix should be on this split (maybe use "String.prototype.match()" instead?):
https://github.com/angular-eslint/angular-eslint/blob/266486e3c9870eb350aac9c7b41a7b8c7d9e5bbc/packages/eslint-plugin-template/src/processors.ts#L53

I don't know if I will be able to work on it this weekend, so if anyone wants to take it, be free. If not I can check that later.

**Comment by JamesHenry** [comment]
Ha I always knew that quick prototyping work I did would stay in until it caused an actual issue. I’ll try and take a look later on, will likely make it AST based instead of string manipulation

**Comment by LouisSung** [comment]
BTW, I find another issue just now. Maybe they can be fixed together by using the AST based approach?

* If I add ***`// prettier-ignore`*** before the `template`, this TypeError raises as shown below.
  + However, **unlike the `:` one**, this Error does NOT stop the other files from linting.

* Sample code
  + ```
    @Component({
      selector: 'app-app-root',
      // prettier-ignore
      template: `<div></div>`,
      styleUrls: ['./app.component.scss']
    })
    ```

* Error message:
  + ```bash
    TypeError: Cannot read property 'length' of undefined
        at /home/LouisSung/Desktop/demo/node_modules/@angular-eslint/eslint-plugin-template/dist/index.js:1:670
        at preprocess (/home/LouisSung/Desktop/demo/node_modules/@angular-eslint/eslint-plugin-template/dist/index.js:1:678)
        at Linter._verifyWithProcessor (/home/LouisSung/Desktop/demo/node_modules/eslint/lib/linter/linter.js:1276:30)
        at Linter._verifyWithConfigArray (/home/LouisSung/Desktop/demo/node_modules/eslint/lib/linter/linter.js:1248:25)
        at Linter.verify (/home/LouisSung/Desktop/demo/node_modules/eslint/lib/linter/linter.js:1210:25)
        at Linter.verifyAndFix (/home/LouisSung/Desktop/demo/node_modules/eslint/lib/linter/linter.js:1400:29)
        at verifyText (/home/LouisSung/Desktop/demo/node_modules/eslint/lib/cli-engine/cli-engine.js:230:48)
        at CLIEngine.executeOnFiles (/home/LouisSung/Desktop/demo/node_modules/eslint/lib/cli-engine/cli-engine.js:798:28)
        at _lint (/home/LouisSung/Desktop/demo/node_modules/@angular-eslint/builder/dist/index.js:1:4507)
        at async _run (/home/LouisSung/Desktop/demo/node_modules/@angular-eslint/builder/dist/index.js:1:5658)
    preprocess: ERROR could not parse @Component() metadata /home/LouisSung/Desktop/demo/apps/demo/src/app/app.component.ts
```

**Comment by JamesHenry** [comment]
Thanks all, I have added all the referenced issues as test cases in #70

**Comment by JamesHenry** [comment]
Released `v0.0.1-alpha.28`

**Comment by IAMtheIAM** [comment]
@digeomel Thanks for sharing your config. I did not realize I needed to configure the .component.html rules separately from the .ts rules, nor did I see anything documenting the existence of `overrides` anywhere. 

Additionally, the repo doesn't explain that we need to use `                "@angular-eslint/template/banana-in-a-box"` in order to use that rule - I was trying just `banana-in-a-box"` and got nothing. Also, I tried it as `"@angular-eslint/template/banana-in-a-box"` but didn't realize we need to add the plugin `["@angular-eslint/template"]` and the parser `"@angular-eslint/template-parser"`. I didn't know about the parser option at all!
`

A valid config object is almost always helpful! I suggest the readme could have some of these things updated to reflect these small little "gotchas".

**Comment by LouisSung** [comment]
I agree that there should have some well written documents but not yet exists _(;3
However, it takes time and effort to do so, that’s why everyone can contribute to this project using PR or even just opening an issue or post their sample code.

I used to struggle to build up lint rules for my project when I was a total beginner for npm and ESLint a few months ago too _(;3
Some of problems are ESLint related rather than this project (e.g., overrides).

Maybe because I started the rules from the JS, TS, then Angular, so I have more time on playing with the built-in rules (I.e., not using plugins).
Just to share some experience that staring from ESLint itself and move onto this project is easier to understand how things work.
I agree that it’s good to have some tutorials rather than let beginners google themselves or do the code review.

ps: there are well comments in this project if you’d like to review some code :D

**Comment by digeomel** [comment]
@IAMtheIAM my config is derived mostly from the links at the top of the file, modified slightly to meet our team requirements. For example, we turned most eslint issues to warnings instead of errors. Also, some rules (or whole blocks) are commented out, especially the one about the typescript-eslint/tslint plugin which kinda defies the purpose of switching from tslint to eslint.
But I have to admit that we still struggle with eslint, especially on the rule about deprecated imports (it's hell on RxJs), to the point where I think it's best to stick to tslint for now until the whole Angular team migrates to eslint.

In any case, I suggest you visit the links I mentioned to get up-to-date example configs and information about them, as things change too fast.

**Comment by ryboucher** [comment]
I am still having this issue out of the box, before even adding any custom eslint rules. It is having an issue parsing this template.

```
@Component({
  selector: 'app-iframe-router',
  template: `
    <app-iframe [url]="url | async"> </app-iframe>
  `,
  styles: []
})
```

**Comment by JamesHenry** [comment]
@ryboucher the Angular CLI workspace in this repo is a good representation of the out of the box behaviour, so please could you apply your code to that workspace and run the appropriate commands to create a reproduction of the issue you are seeing? Then I can investigate.

Thanks!
